<?xml version="1.0" encoding="utf-8"?><Database Name="ModernRetail" Class="ModernRetailDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.MR_BRANCHDETAILSLIST" Member="MR_BRANCHDETAILSLISTs">
    <Type Name="MR_BRANCHDETAILSLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BRANCH_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRANCH_CODE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCHNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PARENTBRANCH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="BRANCH_ADDRESS1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BRANCH_COUNTRY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCH_STATE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCH_CITY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCH_PIN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_COUNTRYMASTERLIST" Member="MR_COUNTRYMASTERLISTs">
    <Type Name="MR_COUNTRYMASTERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="COUNTRYID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COUNTRYNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_STATEMASTERLIST" Member="MR_STATEMASTERLISTs">
    <Type Name="MR_STATEMASTERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="STATEID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATENAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="STATECODE" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="COUNTRYNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEUSER" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYUSER" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_DESIGNATIONMASTERLIST" Member="MR_DESIGNATIONMASTERLISTs">
    <Type Name="MR_DESIGNATIONMASTERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DESIGNATIONID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DESIGNATIONNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_SECURITYROLESLIST" Member="MR_SECURITYROLESLISTs">
    <Type Name="MR_SECURITYROLESLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="GRP_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GRP_NAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_CITYMASTERLIST" Member="MR_CITYMASTERLISTs">
    <Type Name="MR_CITYMASTERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CITYID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITYNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="COUNTRYNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="STATENAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CityLocationLat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CityLocationLong" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEUSER" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYUSER" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_GROUPMEMBERLIST" Member="MR_GROUPMEMBERLISTs">
    <Type Name="MR_GROUPMEMBERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="USER_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="USER_NAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="USER_LOGINID" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="GRSTATUS" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ONLINESTATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DESIGNATION" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_ProductMasterList" Member="MR_ProductMasterLists">
    <Type Name="MR_ProductMasterList">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sProducts_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="sProducts_Code" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="sProducts_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="sProducts_Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProductClass_Code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductClass_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Brand_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Brand_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Size_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="sProduct_Price" Type="System.Decimal" DbType="Decimal(18,5)" CanBeNull="true" />
      <Column Name="sProduct_MRP" Type="System.Decimal" DbType="Decimal(18,5)" CanBeNull="true" />
      <Column Name="sProduct_Status" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="UOM_Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_USERLIST" Member="MR_USERLISTs">
    <Type Name="MR_USERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="USER_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="USER_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_LOGINID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DEPARTMENTNAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DESIGNATIONNAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="REPORTTONAME" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="GROUPNAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="USER_INACTIVE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_BRANDMASTERLIST" Member="MR_BRANDMASTERLISTs">
    <Type Name="MR_BRANDMASTERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Brand_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Brand_Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Brand_ContactNo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Brand_Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_PRODUCTCLASSCATEGORYLIST" Member="MR_PRODUCTCLASSCATEGORYLISTs">
    <Type Name="MR_PRODUCTCLASSCATEGORYLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ProductClass_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductClass_Code" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="ProductClass_Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ProductClass_Description" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_MEASUREMENTS_LIST" Member="MR_MEASUREMENTS_LISTs">
    <Type Name="MR_MEASUREMENTS_LIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Size_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Size_Name" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Size_Description" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_WAREHOUSE_LIST" Member="MR_WAREHOUSE_LISTs">
    <Type Name="MR_WAREHOUSE_LIST">
      <Column Name="SEQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="USERID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="WAREHOUSE_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="WAREHOUSE_NAME" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ADDRESS1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ADDRESS2" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ADDRESS3" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PIN" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CONTACT_NAME" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="CONTACT_PHONE" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="STORE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ISDEFAULT" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CREATE_ON" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_ON" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="UPDATED_BY" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="city_name" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="cou_country" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_PINZIPMASTERLIST" Member="MR_PINZIPMASTERLISTs">
    <Type Name="MR_PINZIPMASTERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="pin_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pin_code" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CITYNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="COUNTRYNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="STATENAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEUSER" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYUSER" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_STOREMASTERLIST" Member="MR_STOREMASTERLISTs">
    <Type Name="MR_STOREMASTERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="STORE_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STORE_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="STORE_ADDRESS" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="STORE_PINCODE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STORE_BRANCH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STORE_CONTACT_NUMBER" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="STORE_TYPE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STORE_WHATSAPP_NUMBER" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="STORE_EMAIL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STORE_IMAGE" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STORE_CREATEDUSER" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="STORE_ISACTIVE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_PRODUCTBRANCHMAPLIST" Member="MR_PRODUCTBRANCHMAPLISTs">
    <Type Name="MR_PRODUCTBRANCHMAPLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PRODUCTBRANCHMAP_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BRANCH_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRANCHNAME" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="PRODUCT_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PRODUCT_CODE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PRODUCTS_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PARENTEMP_USERID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PARENTEMP_NAME" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="CHILDEMP_USERID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CHILDEMP_NAME" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_DEPARTMENTMASTERLIST" Member="MR_DEPARTMENTMASTERLISTs">
    <Type Name="MR_DEPARTMENTMASTERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DEPARTMENTID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DEPARTMENTNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_GROUPBEATLIST" Member="V_GROUPBEATLISTs">
    <Type Name="V_GROUPBEATLIST">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Beat_Code" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Beat_Name" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Created_By" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Created_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated_By" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Updated_On" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CODE_TYPE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="AREANAME" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ROUTENAME" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="BEATNAME" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MR_MAPUSERLIST" Member="MR_MAPUSERLISTs">
    <Type Name="MR_MAPUSERLIST">
      <Column Name="userid" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="seq" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="user_id" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="user_loginId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MR_BEATPLANLIST" Member="MR_BEATPLANLISTs">
    <Type Name="MR_BEATPLANLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PLAN_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FROM_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TO_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EMPNAME" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="BEATNAME" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ROUTENAME" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AREANAME" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DEVIATION" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DEV_BEATNAME" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="CreateOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateBy" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="UpdateOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_PJPLIST_REPORT" Member="MR_PJPLIST_REPORTs">
    <Type Name="MR_PJPLIST_REPORT">
      <Column Name="USERID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PJP_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="PJP_DATE" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="From_Time" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="To_Time" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SHOP_CODE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Shop_Name" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="EMP_NAME" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="EMP_ID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Supervisor" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Supervisor_ID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Emp_Phone" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Supervisor_Phone" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_CURRENTSTOCK_LISTING" Member="MR_CURRENTSTOCK_LISTINGs">
    <Type Name="MR_CURRENTSTOCK_LISTING">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STOCK_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STORENAME" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CURRENTSTOCKDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TOTAL_ITEMS" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TOTAL_QUANTITY" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFIED_BY" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="MODIFIED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_PRODUCTRATESDETAILSLIST" Member="MR_PRODUCTRATESDETAILSLISTs">
    <Type Name="MR_PRODUCTRATESDETAILSLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRODUCT_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="STATE_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BRANCH_ID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="STORE_RATE" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PRODUCT_CODE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PRODUCT_NAME" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="STATE_NAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="STORE_ID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="STORE_NAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_FORMTYPELIST" Member="MR_FORMTYPELISTs">
    <Type Name="MR_FORMTYPELIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FORMTYPE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FORMTYPE_SURVEYDESC" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FORMTYPE_REMARKS" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="FORMTYPE_SECGROUPNAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FORMTYPE_ISACTIVE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CREATEDON" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEDBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MODIFIEDON" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFIEDBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>