#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernRetail.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ModernRetail")]
	public partial class ModernRetailDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ModernRetailDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModernRetailDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModernRetailDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModernRetailDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MR_BRANCHDETAILSLIST> MR_BRANCHDETAILSLISTs
		{
			get
			{
				return this.GetTable<MR_BRANCHDETAILSLIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_COUNTRYMASTERLIST> MR_COUNTRYMASTERLISTs
		{
			get
			{
				return this.GetTable<MR_COUNTRYMASTERLIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_STATEMASTERLIST> MR_STATEMASTERLISTs
		{
			get
			{
				return this.GetTable<MR_STATEMASTERLIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_DESIGNATIONMASTERLIST> MR_DESIGNATIONMASTERLISTs
		{
			get
			{
				return this.GetTable<MR_DESIGNATIONMASTERLIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_SECURITYROLESLIST> MR_SECURITYROLESLISTs
		{
			get
			{
				return this.GetTable<MR_SECURITYROLESLIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_CITYMASTERLIST> MR_CITYMASTERLISTs
		{
			get
			{
				return this.GetTable<MR_CITYMASTERLIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_GROUPMEMBERLIST> MR_GROUPMEMBERLISTs
		{
			get
			{
				return this.GetTable<MR_GROUPMEMBERLIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_ProductMasterList> MR_ProductMasterLists
		{
			get
			{
				return this.GetTable<MR_ProductMasterList>();
			}
		}
		
		public System.Data.Linq.Table<MR_USERLIST> MR_USERLISTs
		{
			get
			{
				return this.GetTable<MR_USERLIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_BRANDMASTERLIST> MR_BRANDMASTERLISTs
		{
			get
			{
				return this.GetTable<MR_BRANDMASTERLIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_PRODUCTCLASSCATEGORYLIST> MR_PRODUCTCLASSCATEGORYLISTs
		{
			get
			{
				return this.GetTable<MR_PRODUCTCLASSCATEGORYLIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_CURRENTSTOCK_LISTING> MR_CURRENTSTOCK_LISTINGs
		{
			get
			{
				return this.GetTable<MR_CURRENTSTOCK_LISTING>();
			}
		}
		
		public System.Data.Linq.Table<MR_MEASUREMENTS_LIST> MR_MEASUREMENTS_LISTs
		{
			get
			{
				return this.GetTable<MR_MEASUREMENTS_LIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_WAREHOUSE_LIST> MR_WAREHOUSE_LISTs
		{
			get
			{
				return this.GetTable<MR_WAREHOUSE_LIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_PRODUCTRATESDETAILSLIST> MR_PRODUCTRATESDETAILSLISTs
		{
			get
			{
				return this.GetTable<MR_PRODUCTRATESDETAILSLIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_PINZIPMASTERLIST> MR_PINZIPMASTERLISTs
		{
			get
			{
				return this.GetTable<MR_PINZIPMASTERLIST>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_BRANCHDETAILSLIST")]
	public partial class MR_BRANCHDETAILSLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _BRANCH_ID;
		
		private string _BRANCH_CODE;
		
		private string _BRANCHNAME;
		
		private string _PARENTBRANCH;
		
		private string _BRANCH_ADDRESS1;
		
		private string _BRANCH_COUNTRY;
		
		private string _BRANCH_STATE;
		
		private string _BRANCH_CITY;
		
		private string _BRANCH_PIN;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateUser;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyUser;
		
		public MR_BRANCHDETAILSLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_ID", DbType="Int")]
		public System.Nullable<int> BRANCH_ID
		{
			get
			{
				return this._BRANCH_ID;
			}
			set
			{
				if ((this._BRANCH_ID != value))
				{
					this._BRANCH_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_CODE", DbType="NVarChar(100)")]
		public string BRANCH_CODE
		{
			get
			{
				return this._BRANCH_CODE;
			}
			set
			{
				if ((this._BRANCH_CODE != value))
				{
					this._BRANCH_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCHNAME", DbType="NVarChar(250)")]
		public string BRANCHNAME
		{
			get
			{
				return this._BRANCHNAME;
			}
			set
			{
				if ((this._BRANCHNAME != value))
				{
					this._BRANCHNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENTBRANCH", DbType="NVarChar(250)")]
		public string PARENTBRANCH
		{
			get
			{
				return this._PARENTBRANCH;
			}
			set
			{
				if ((this._PARENTBRANCH != value))
				{
					this._PARENTBRANCH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_ADDRESS1", DbType="NVarChar(500)")]
		public string BRANCH_ADDRESS1
		{
			get
			{
				return this._BRANCH_ADDRESS1;
			}
			set
			{
				if ((this._BRANCH_ADDRESS1 != value))
				{
					this._BRANCH_ADDRESS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_COUNTRY", DbType="NVarChar(100)")]
		public string BRANCH_COUNTRY
		{
			get
			{
				return this._BRANCH_COUNTRY;
			}
			set
			{
				if ((this._BRANCH_COUNTRY != value))
				{
					this._BRANCH_COUNTRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_STATE", DbType="NVarChar(100)")]
		public string BRANCH_STATE
		{
			get
			{
				return this._BRANCH_STATE;
			}
			set
			{
				if ((this._BRANCH_STATE != value))
				{
					this._BRANCH_STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_CITY", DbType="NVarChar(100)")]
		public string BRANCH_CITY
		{
			get
			{
				return this._BRANCH_CITY;
			}
			set
			{
				if ((this._BRANCH_CITY != value))
				{
					this._BRANCH_CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_PIN", DbType="NVarChar(100)")]
		public string BRANCH_PIN
		{
			get
			{
				return this._BRANCH_PIN;
			}
			set
			{
				if ((this._BRANCH_PIN != value))
				{
					this._BRANCH_PIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="NVarChar(100)")]
		public string CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this._CreateUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyUser", DbType="NVarChar(100)")]
		public string ModifyUser
		{
			get
			{
				return this._ModifyUser;
			}
			set
			{
				if ((this._ModifyUser != value))
				{
					this._ModifyUser = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_COUNTRYMASTERLIST")]
	public partial class MR_COUNTRYMASTERLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _COUNTRYID;
		
		private string _COUNTRYNAME;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateUser;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyUser;
		
		public MR_COUNTRYMASTERLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYID", DbType="Int")]
		public System.Nullable<int> COUNTRYID
		{
			get
			{
				return this._COUNTRYID;
			}
			set
			{
				if ((this._COUNTRYID != value))
				{
					this._COUNTRYID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYNAME", DbType="NVarChar(250)")]
		public string COUNTRYNAME
		{
			get
			{
				return this._COUNTRYNAME;
			}
			set
			{
				if ((this._COUNTRYNAME != value))
				{
					this._COUNTRYNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="NVarChar(100)")]
		public string CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this._CreateUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyUser", DbType="NVarChar(100)")]
		public string ModifyUser
		{
			get
			{
				return this._ModifyUser;
			}
			set
			{
				if ((this._ModifyUser != value))
				{
					this._ModifyUser = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_STATEMASTERLIST")]
	public partial class MR_STATEMASTERLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _STATEID;
		
		private string _STATENAME;
		
		private string _STATECODE;
		
		private string _COUNTRYNAME;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _CREATEUSER;
		
		private System.Nullable<System.DateTime> _MODIFYDATE;
		
		private string _MODIFYUSER;
		
		public MR_STATEMASTERLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATEID", DbType="Int")]
		public System.Nullable<int> STATEID
		{
			get
			{
				return this._STATEID;
			}
			set
			{
				if ((this._STATEID != value))
				{
					this._STATEID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATENAME", DbType="NVarChar(250)")]
		public string STATENAME
		{
			get
			{
				return this._STATENAME;
			}
			set
			{
				if ((this._STATENAME != value))
				{
					this._STATENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATECODE", DbType="NVarChar(250)")]
		public string STATECODE
		{
			get
			{
				return this._STATECODE;
			}
			set
			{
				if ((this._STATECODE != value))
				{
					this._STATECODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYNAME", DbType="NVarChar(250)")]
		public string COUNTRYNAME
		{
			get
			{
				return this._COUNTRYNAME;
			}
			set
			{
				if ((this._COUNTRYNAME != value))
				{
					this._COUNTRYNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this._CREATEDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEUSER", DbType="NVarChar(100)")]
		public string CREATEUSER
		{
			get
			{
				return this._CREATEUSER;
			}
			set
			{
				if ((this._CREATEUSER != value))
				{
					this._CREATEUSER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFYDATE
		{
			get
			{
				return this._MODIFYDATE;
			}
			set
			{
				if ((this._MODIFYDATE != value))
				{
					this._MODIFYDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYUSER", DbType="NVarChar(100)")]
		public string MODIFYUSER
		{
			get
			{
				return this._MODIFYUSER;
			}
			set
			{
				if ((this._MODIFYUSER != value))
				{
					this._MODIFYUSER = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_DESIGNATIONMASTERLIST")]
	public partial class MR_DESIGNATIONMASTERLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _DESIGNATIONID;
		
		private string _DESIGNATIONNAME;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateUser;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyUser;
		
		public MR_DESIGNATIONMASTERLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESIGNATIONID", DbType="Int")]
		public System.Nullable<int> DESIGNATIONID
		{
			get
			{
				return this._DESIGNATIONID;
			}
			set
			{
				if ((this._DESIGNATIONID != value))
				{
					this._DESIGNATIONID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESIGNATIONNAME", DbType="NVarChar(250)")]
		public string DESIGNATIONNAME
		{
			get
			{
				return this._DESIGNATIONNAME;
			}
			set
			{
				if ((this._DESIGNATIONNAME != value))
				{
					this._DESIGNATIONNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="NVarChar(100)")]
		public string CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this._CreateUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyUser", DbType="NVarChar(100)")]
		public string ModifyUser
		{
			get
			{
				return this._ModifyUser;
			}
			set
			{
				if ((this._ModifyUser != value))
				{
					this._ModifyUser = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_SECURITYROLESLIST")]
	public partial class MR_SECURITYROLESLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _GRP_ID;
		
		private string _GRP_NAME;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateUser;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyUser;
		
		public MR_SECURITYROLESLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRP_ID", DbType="Int")]
		public System.Nullable<int> GRP_ID
		{
			get
			{
				return this._GRP_ID;
			}
			set
			{
				if ((this._GRP_ID != value))
				{
					this._GRP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRP_NAME", DbType="NVarChar(250)")]
		public string GRP_NAME
		{
			get
			{
				return this._GRP_NAME;
			}
			set
			{
				if ((this._GRP_NAME != value))
				{
					this._GRP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="NVarChar(100)")]
		public string CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this._CreateUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyUser", DbType="NVarChar(100)")]
		public string ModifyUser
		{
			get
			{
				return this._ModifyUser;
			}
			set
			{
				if ((this._ModifyUser != value))
				{
					this._ModifyUser = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_CITYMASTERLIST")]
	public partial class MR_CITYMASTERLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _CITYID;
		
		private string _CITYNAME;
		
		private string _COUNTRYNAME;
		
		private string _STATENAME;
		
		private string _CityLocationLat;
		
		private string _CityLocationLong;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _CREATEUSER;
		
		private System.Nullable<System.DateTime> _MODIFYDATE;
		
		private string _MODIFYUSER;
		
		public MR_CITYMASTERLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITYID", DbType="Int")]
		public System.Nullable<int> CITYID
		{
			get
			{
				return this._CITYID;
			}
			set
			{
				if ((this._CITYID != value))
				{
					this._CITYID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITYNAME", DbType="NVarChar(250)")]
		public string CITYNAME
		{
			get
			{
				return this._CITYNAME;
			}
			set
			{
				if ((this._CITYNAME != value))
				{
					this._CITYNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYNAME", DbType="NVarChar(250)")]
		public string COUNTRYNAME
		{
			get
			{
				return this._COUNTRYNAME;
			}
			set
			{
				if ((this._COUNTRYNAME != value))
				{
					this._COUNTRYNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATENAME", DbType="NVarChar(250)")]
		public string STATENAME
		{
			get
			{
				return this._STATENAME;
			}
			set
			{
				if ((this._STATENAME != value))
				{
					this._STATENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityLocationLat", DbType="NVarChar(MAX)")]
		public string CityLocationLat
		{
			get
			{
				return this._CityLocationLat;
			}
			set
			{
				if ((this._CityLocationLat != value))
				{
					this._CityLocationLat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityLocationLong", DbType="NVarChar(MAX)")]
		public string CityLocationLong
		{
			get
			{
				return this._CityLocationLong;
			}
			set
			{
				if ((this._CityLocationLong != value))
				{
					this._CityLocationLong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this._CREATEDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEUSER", DbType="NVarChar(100)")]
		public string CREATEUSER
		{
			get
			{
				return this._CREATEUSER;
			}
			set
			{
				if ((this._CREATEUSER != value))
				{
					this._CREATEUSER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFYDATE
		{
			get
			{
				return this._MODIFYDATE;
			}
			set
			{
				if ((this._MODIFYDATE != value))
				{
					this._MODIFYDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYUSER", DbType="NVarChar(100)")]
		public string MODIFYUSER
		{
			get
			{
				return this._MODIFYUSER;
			}
			set
			{
				if ((this._MODIFYUSER != value))
				{
					this._MODIFYUSER = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_GROUPMEMBERLIST")]
	public partial class MR_GROUPMEMBERLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<long> _USER_ID;
		
		private string _USER_NAME;
		
		private string _USER_LOGINID;
		
		private string _GRSTATUS;
		
		private System.Nullable<int> _ONLINESTATUS;
		
		private string _DESIGNATION;
		
		public MR_GROUPMEMBERLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="BigInt")]
		public System.Nullable<long> USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this._USER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="NVarChar(250)")]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this._USER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_LOGINID", DbType="NVarChar(250)")]
		public string USER_LOGINID
		{
			get
			{
				return this._USER_LOGINID;
			}
			set
			{
				if ((this._USER_LOGINID != value))
				{
					this._USER_LOGINID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRSTATUS", DbType="NVarChar(100)")]
		public string GRSTATUS
		{
			get
			{
				return this._GRSTATUS;
			}
			set
			{
				if ((this._GRSTATUS != value))
				{
					this._GRSTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ONLINESTATUS", DbType="Int")]
		public System.Nullable<int> ONLINESTATUS
		{
			get
			{
				return this._ONLINESTATUS;
			}
			set
			{
				if ((this._ONLINESTATUS != value))
				{
					this._ONLINESTATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESIGNATION", DbType="NVarChar(200)")]
		public string DESIGNATION
		{
			get
			{
				return this._DESIGNATION;
			}
			set
			{
				if ((this._DESIGNATION != value))
				{
					this._DESIGNATION = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_ProductMasterList")]
	public partial class MR_ProductMasterList
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _sProducts_ID;
		
		private string _sProducts_Code;
		
		private string _sProducts_Name;
		
		private string _sProducts_Description;
		
		private System.Nullable<int> _ProductClass_Code;
		
		private string _ProductClass_Name;
		
		private System.Nullable<int> _Brand_Id;
		
		private string _Brand_Name;
		
		private string _Size_Name;
		
		private System.Nullable<decimal> _sProduct_Price;
		
		private System.Nullable<decimal> _sProduct_MRP;
		
		private string _sProduct_Status;
		
		private string _UOM_Name;
		
		public MR_ProductMasterList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sProducts_ID", DbType="BigInt")]
		public System.Nullable<long> sProducts_ID
		{
			get
			{
				return this._sProducts_ID;
			}
			set
			{
				if ((this._sProducts_ID != value))
				{
					this._sProducts_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sProducts_Code", DbType="VarChar(80)")]
		public string sProducts_Code
		{
			get
			{
				return this._sProducts_Code;
			}
			set
			{
				if ((this._sProducts_Code != value))
				{
					this._sProducts_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sProducts_Name", DbType="VarChar(100)")]
		public string sProducts_Name
		{
			get
			{
				return this._sProducts_Name;
			}
			set
			{
				if ((this._sProducts_Name != value))
				{
					this._sProducts_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sProducts_Description", DbType="NVarChar(MAX)")]
		public string sProducts_Description
		{
			get
			{
				return this._sProducts_Description;
			}
			set
			{
				if ((this._sProducts_Description != value))
				{
					this._sProducts_Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductClass_Code", DbType="Int")]
		public System.Nullable<int> ProductClass_Code
		{
			get
			{
				return this._ProductClass_Code;
			}
			set
			{
				if ((this._ProductClass_Code != value))
				{
					this._ProductClass_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductClass_Name", DbType="VarChar(100)")]
		public string ProductClass_Name
		{
			get
			{
				return this._ProductClass_Name;
			}
			set
			{
				if ((this._ProductClass_Name != value))
				{
					this._ProductClass_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand_Id", DbType="Int")]
		public System.Nullable<int> Brand_Id
		{
			get
			{
				return this._Brand_Id;
			}
			set
			{
				if ((this._Brand_Id != value))
				{
					this._Brand_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand_Name", DbType="VarChar(50)")]
		public string Brand_Name
		{
			get
			{
				return this._Brand_Name;
			}
			set
			{
				if ((this._Brand_Name != value))
				{
					this._Brand_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size_Name", DbType="VarChar(30)")]
		public string Size_Name
		{
			get
			{
				return this._Size_Name;
			}
			set
			{
				if ((this._Size_Name != value))
				{
					this._Size_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sProduct_Price", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> sProduct_Price
		{
			get
			{
				return this._sProduct_Price;
			}
			set
			{
				if ((this._sProduct_Price != value))
				{
					this._sProduct_Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sProduct_MRP", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> sProduct_MRP
		{
			get
			{
				return this._sProduct_MRP;
			}
			set
			{
				if ((this._sProduct_MRP != value))
				{
					this._sProduct_MRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sProduct_Status", DbType="VarChar(15)")]
		public string sProduct_Status
		{
			get
			{
				return this._sProduct_Status;
			}
			set
			{
				if ((this._sProduct_Status != value))
				{
					this._sProduct_Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UOM_Name", DbType="NVarChar(200)")]
		public string UOM_Name
		{
			get
			{
				return this._UOM_Name;
			}
			set
			{
				if ((this._UOM_Name != value))
				{
					this._UOM_Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_USERLIST")]
	public partial class MR_USERLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<long> _USER_ID;
		
		private string _USER_NAME;
		
		private string _USER_LOGINID;
		
		private string _DEPARTMENTNAME;
		
		private string _DESIGNATIONNAME;
		
		private string _REPORTTONAME;
		
		private string _GROUPNAME;
		
		private string _CREATEDATE;
		
		private string _USER_INACTIVE;
		
		public MR_USERLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="BigInt")]
		public System.Nullable<long> USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this._USER_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="VarChar(50)")]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this._USER_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_LOGINID", DbType="VarChar(50)")]
		public string USER_LOGINID
		{
			get
			{
				return this._USER_LOGINID;
			}
			set
			{
				if ((this._USER_LOGINID != value))
				{
					this._USER_LOGINID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENTNAME", DbType="VarChar(200)")]
		public string DEPARTMENTNAME
		{
			get
			{
				return this._DEPARTMENTNAME;
			}
			set
			{
				if ((this._DEPARTMENTNAME != value))
				{
					this._DEPARTMENTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESIGNATIONNAME", DbType="VarChar(200)")]
		public string DESIGNATIONNAME
		{
			get
			{
				return this._DESIGNATIONNAME;
			}
			set
			{
				if ((this._DESIGNATIONNAME != value))
				{
					this._DESIGNATIONNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPORTTONAME", DbType="VarChar(300)")]
		public string REPORTTONAME
		{
			get
			{
				return this._REPORTTONAME;
			}
			set
			{
				if ((this._REPORTTONAME != value))
				{
					this._REPORTTONAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GROUPNAME", DbType="VarChar(200)")]
		public string GROUPNAME
		{
			get
			{
				return this._GROUPNAME;
			}
			set
			{
				if ((this._GROUPNAME != value))
				{
					this._GROUPNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="VarChar(100)")]
		public string CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this._CREATEDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_INACTIVE", DbType="VarChar(10)")]
		public string USER_INACTIVE
		{
			get
			{
				return this._USER_INACTIVE;
			}
			set
			{
				if ((this._USER_INACTIVE != value))
				{
					this._USER_INACTIVE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_BRANDMASTERLIST")]
	public partial class MR_BRANDMASTERLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _Brand_Id;
		
		private string _Brand_Name;
		
		private string _Brand_ContactNo;
		
		private string _Brand_Email;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateUser;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyUser;
		
		public MR_BRANDMASTERLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand_Id", DbType="Int")]
		public System.Nullable<int> Brand_Id
		{
			get
			{
				return this._Brand_Id;
			}
			set
			{
				if ((this._Brand_Id != value))
				{
					this._Brand_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand_Name", DbType="NVarChar(250)")]
		public string Brand_Name
		{
			get
			{
				return this._Brand_Name;
			}
			set
			{
				if ((this._Brand_Name != value))
				{
					this._Brand_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand_ContactNo", DbType="VarChar(100)")]
		public string Brand_ContactNo
		{
			get
			{
				return this._Brand_ContactNo;
			}
			set
			{
				if ((this._Brand_ContactNo != value))
				{
					this._Brand_ContactNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brand_Email", DbType="VarChar(100)")]
		public string Brand_Email
		{
			get
			{
				return this._Brand_Email;
			}
			set
			{
				if ((this._Brand_Email != value))
				{
					this._Brand_Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="NVarChar(200)")]
		public string CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this._CreateUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyUser", DbType="NVarChar(200)")]
		public string ModifyUser
		{
			get
			{
				return this._ModifyUser;
			}
			set
			{
				if ((this._ModifyUser != value))
				{
					this._ModifyUser = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_PRODUCTCLASSCATEGORYLIST")]
	public partial class MR_PRODUCTCLASSCATEGORYLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _ProductClass_ID;
		
		private string _ProductClass_Code;
		
		private string _ProductClass_Name;
		
		private string _ProductClass_Description;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateUser;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyUser;
		
		public MR_PRODUCTCLASSCATEGORYLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductClass_ID", DbType="Int")]
		public System.Nullable<int> ProductClass_ID
		{
			get
			{
				return this._ProductClass_ID;
			}
			set
			{
				if ((this._ProductClass_ID != value))
				{
					this._ProductClass_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductClass_Code", DbType="NVarChar(80)")]
		public string ProductClass_Code
		{
			get
			{
				return this._ProductClass_Code;
			}
			set
			{
				if ((this._ProductClass_Code != value))
				{
					this._ProductClass_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductClass_Name", DbType="VarChar(100)")]
		public string ProductClass_Name
		{
			get
			{
				return this._ProductClass_Name;
			}
			set
			{
				if ((this._ProductClass_Name != value))
				{
					this._ProductClass_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductClass_Description", DbType="VarChar(300)")]
		public string ProductClass_Description
		{
			get
			{
				return this._ProductClass_Description;
			}
			set
			{
				if ((this._ProductClass_Description != value))
				{
					this._ProductClass_Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="NVarChar(200)")]
		public string CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this._CreateUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyUser", DbType="NVarChar(200)")]
		public string ModifyUser
		{
			get
			{
				return this._ModifyUser;
			}
			set
			{
				if ((this._ModifyUser != value))
				{
					this._ModifyUser = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_CURRENTSTOCK_LISTING")]
	public partial class MR_CURRENTSTOCK_LISTING
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<int> _SEQ;
		
		private System.Nullable<long> _STOCK_ID;
		
		private string _BRANCH;
		
		private string _SHOPNAME;
		
		private string _CODE;
		
		private string _CONTACTNUMBER;
		
		private string _SHOPTYPE;
		
		private System.Nullable<System.DateTime> _CURRENTSTOCKDATE;
		
		private string _PRODUCTCODE;
		
		private string _PRODUCTNAME;
		
		private System.Nullable<decimal> _QUANTITY;
		
		private System.Nullable<decimal> _QUANTITY_BAL;
		
		private string _CREATED_BY;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private string _MODIFIED_BY;
		
		private System.Nullable<System.DateTime> _MODIFIED_DATE;
		
		public MR_CURRENTSTOCK_LISTING()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="Int")]
		public System.Nullable<int> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOCK_ID", DbType="BigInt")]
		public System.Nullable<long> STOCK_ID
		{
			get
			{
				return this._STOCK_ID;
			}
			set
			{
				if ((this._STOCK_ID != value))
				{
					this._STOCK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH", DbType="VarChar(500)")]
		public string BRANCH
		{
			get
			{
				return this._BRANCH;
			}
			set
			{
				if ((this._BRANCH != value))
				{
					this._BRANCH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHOPNAME", DbType="NVarChar(500)")]
		public string SHOPNAME
		{
			get
			{
				return this._SHOPNAME;
			}
			set
			{
				if ((this._SHOPNAME != value))
				{
					this._SHOPNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(50)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this._CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACTNUMBER", DbType="NVarChar(500)")]
		public string CONTACTNUMBER
		{
			get
			{
				return this._CONTACTNUMBER;
			}
			set
			{
				if ((this._CONTACTNUMBER != value))
				{
					this._CONTACTNUMBER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHOPTYPE", DbType="VarChar(500)")]
		public string SHOPTYPE
		{
			get
			{
				return this._SHOPTYPE;
			}
			set
			{
				if ((this._SHOPTYPE != value))
				{
					this._SHOPTYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENTSTOCKDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CURRENTSTOCKDATE
		{
			get
			{
				return this._CURRENTSTOCKDATE;
			}
			set
			{
				if ((this._CURRENTSTOCKDATE != value))
				{
					this._CURRENTSTOCKDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTCODE", DbType="NVarChar(500)")]
		public string PRODUCTCODE
		{
			get
			{
				return this._PRODUCTCODE;
			}
			set
			{
				if ((this._PRODUCTCODE != value))
				{
					this._PRODUCTCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCTNAME", DbType="NVarChar(500)")]
		public string PRODUCTNAME
		{
			get
			{
				return this._PRODUCTNAME;
			}
			set
			{
				if ((this._PRODUCTNAME != value))
				{
					this._PRODUCTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> QUANTITY
		{
			get
			{
				return this._QUANTITY;
			}
			set
			{
				if ((this._QUANTITY != value))
				{
					this._QUANTITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANTITY_BAL", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> QUANTITY_BAL
		{
			get
			{
				return this._QUANTITY_BAL;
			}
			set
			{
				if ((this._QUANTITY_BAL != value))
				{
					this._QUANTITY_BAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY", DbType="VarChar(200)")]
		public string CREATED_BY
		{
			get
			{
				return this._CREATED_BY;
			}
			set
			{
				if ((this._CREATED_BY != value))
				{
					this._CREATED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this._CREATED_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_BY", DbType="VarChar(200)")]
		public string MODIFIED_BY
		{
			get
			{
				return this._MODIFIED_BY;
			}
			set
			{
				if ((this._MODIFIED_BY != value))
				{
					this._MODIFIED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFIED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFIED_DATE
		{
			get
			{
				return this._MODIFIED_DATE;
			}
			set
			{
				if ((this._MODIFIED_DATE != value))
				{
					this._MODIFIED_DATE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_MEASUREMENTS_LIST")]
	public partial class MR_MEASUREMENTS_LIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _Size_ID;
		
		private string _Size_Name;
		
		private string _Size_Description;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateUser;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyUser;
		
		public MR_MEASUREMENTS_LIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size_ID", DbType="Int")]
		public System.Nullable<int> Size_ID
		{
			get
			{
				return this._Size_ID;
			}
			set
			{
				if ((this._Size_ID != value))
				{
					this._Size_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size_Name", DbType="VarChar(30)")]
		public string Size_Name
		{
			get
			{
				return this._Size_Name;
			}
			set
			{
				if ((this._Size_Name != value))
				{
					this._Size_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size_Description", DbType="VarChar(150)")]
		public string Size_Description
		{
			get
			{
				return this._Size_Description;
			}
			set
			{
				if ((this._Size_Description != value))
				{
					this._Size_Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="NVarChar(200)")]
		public string CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this._CreateUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyUser", DbType="NVarChar(200)")]
		public string ModifyUser
		{
			get
			{
				return this._ModifyUser;
			}
			set
			{
				if ((this._ModifyUser != value))
				{
					this._ModifyUser = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_WAREHOUSE_LIST")]
	public partial class MR_WAREHOUSE_LIST
	{
		
		private System.Nullable<int> _SEQ;
		
		private System.Nullable<long> _USERID;
		
		private System.Nullable<long> _WAREHOUSE_ID;
		
		private string _WAREHOUSE_NAME;
		
		private string _ADDRESS1;
		
		private string _ADDRESS2;
		
		private string _ADDRESS3;
		
		private string _PIN;
		
		private string _CONTACT_NAME;
		
		private string _CONTACT_PHONE;
		
		private string _STORE_NAME;
		
		private string _ISDEFAULT;
		
		private System.Nullable<System.DateTime> _CREATE_ON;
		
		private System.Nullable<System.DateTime> _UPDATE_ON;
		
		private string _CREATED_BY;
		
		private string _UPDATED_BY;
		
		private string _city_name;
		
		private string _state;
		
		private string _cou_country;
		
		public MR_WAREHOUSE_LIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="Int")]
		public System.Nullable<int> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="BigInt")]
		public System.Nullable<long> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAREHOUSE_ID", DbType="BigInt")]
		public System.Nullable<long> WAREHOUSE_ID
		{
			get
			{
				return this._WAREHOUSE_ID;
			}
			set
			{
				if ((this._WAREHOUSE_ID != value))
				{
					this._WAREHOUSE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WAREHOUSE_NAME", DbType="NVarChar(300)")]
		public string WAREHOUSE_NAME
		{
			get
			{
				return this._WAREHOUSE_NAME;
			}
			set
			{
				if ((this._WAREHOUSE_NAME != value))
				{
					this._WAREHOUSE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS1", DbType="NVarChar(500)")]
		public string ADDRESS1
		{
			get
			{
				return this._ADDRESS1;
			}
			set
			{
				if ((this._ADDRESS1 != value))
				{
					this._ADDRESS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS2", DbType="NVarChar(500)")]
		public string ADDRESS2
		{
			get
			{
				return this._ADDRESS2;
			}
			set
			{
				if ((this._ADDRESS2 != value))
				{
					this._ADDRESS2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS3", DbType="NVarChar(500)")]
		public string ADDRESS3
		{
			get
			{
				return this._ADDRESS3;
			}
			set
			{
				if ((this._ADDRESS3 != value))
				{
					this._ADDRESS3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIN", DbType="NVarChar(10)")]
		public string PIN
		{
			get
			{
				return this._PIN;
			}
			set
			{
				if ((this._PIN != value))
				{
					this._PIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT_NAME", DbType="NVarChar(300)")]
		public string CONTACT_NAME
		{
			get
			{
				return this._CONTACT_NAME;
			}
			set
			{
				if ((this._CONTACT_NAME != value))
				{
					this._CONTACT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTACT_PHONE", DbType="NVarChar(15)")]
		public string CONTACT_PHONE
		{
			get
			{
				return this._CONTACT_PHONE;
			}
			set
			{
				if ((this._CONTACT_PHONE != value))
				{
					this._CONTACT_PHONE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STORE_NAME", DbType="NVarChar(MAX)")]
		public string STORE_NAME
		{
			get
			{
				return this._STORE_NAME;
			}
			set
			{
				if ((this._STORE_NAME != value))
				{
					this._STORE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISDEFAULT", DbType="NVarChar(10)")]
		public string ISDEFAULT
		{
			get
			{
				return this._ISDEFAULT;
			}
			set
			{
				if ((this._ISDEFAULT != value))
				{
					this._ISDEFAULT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_ON", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_ON
		{
			get
			{
				return this._CREATE_ON;
			}
			set
			{
				if ((this._CREATE_ON != value))
				{
					this._CREATE_ON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_ON", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATE_ON
		{
			get
			{
				return this._UPDATE_ON;
			}
			set
			{
				if ((this._UPDATE_ON != value))
				{
					this._UPDATE_ON = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY", DbType="NVarChar(300)")]
		public string CREATED_BY
		{
			get
			{
				return this._CREATED_BY;
			}
			set
			{
				if ((this._CREATED_BY != value))
				{
					this._CREATED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_BY", DbType="NVarChar(300)")]
		public string UPDATED_BY
		{
			get
			{
				return this._UPDATED_BY;
			}
			set
			{
				if ((this._UPDATED_BY != value))
				{
					this._UPDATED_BY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city_name", DbType="NVarChar(300)")]
		public string city_name
		{
			get
			{
				return this._city_name;
			}
			set
			{
				if ((this._city_name != value))
				{
					this._city_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="NVarChar(300)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cou_country", DbType="NVarChar(300)")]
		public string cou_country
		{
			get
			{
				return this._cou_country;
			}
			set
			{
				if ((this._cou_country != value))
				{
					this._cou_country = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_PRODUCTRATESDETAILSLIST")]
	public partial class MR_PRODUCTRATESDETAILSLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _ID;
		
		private System.Nullable<long> _PRODUCT_ID;
		
		private System.Nullable<long> _STATE_ID;
		
		private System.Nullable<long> _BRANCH_ID;
		
		private System.Nullable<long> _DESIGID;
		
		private System.Nullable<long> _EMP_ID;
		
		private System.Nullable<decimal> _STORE_RATE;
		
		private string _PRODUCT_CODE;
		
		private string _PRODUCT_NAME;
		
		private string _BRANCH;
		
		private string _STATE_NAME;
		
		private string _DESIGNATION;
		
		private string _EMP_NAME;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateUser;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyUser;
		
		public MR_PRODUCTRATESDETAILSLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int")]
		public System.Nullable<int> ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_ID", DbType="BigInt")]
		public System.Nullable<long> PRODUCT_ID
		{
			get
			{
				return this._PRODUCT_ID;
			}
			set
			{
				if ((this._PRODUCT_ID != value))
				{
					this._PRODUCT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_ID", DbType="BigInt")]
		public System.Nullable<long> STATE_ID
		{
			get
			{
				return this._STATE_ID;
			}
			set
			{
				if ((this._STATE_ID != value))
				{
					this._STATE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_ID", DbType="BigInt")]
		public System.Nullable<long> BRANCH_ID
		{
			get
			{
				return this._BRANCH_ID;
			}
			set
			{
				if ((this._BRANCH_ID != value))
				{
					this._BRANCH_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESIGID", DbType="BigInt")]
		public System.Nullable<long> DESIGID
		{
			get
			{
				return this._DESIGID;
			}
			set
			{
				if ((this._DESIGID != value))
				{
					this._DESIGID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_ID", DbType="BigInt")]
		public System.Nullable<long> EMP_ID
		{
			get
			{
				return this._EMP_ID;
			}
			set
			{
				if ((this._EMP_ID != value))
				{
					this._EMP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STORE_RATE", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> STORE_RATE
		{
			get
			{
				return this._STORE_RATE;
			}
			set
			{
				if ((this._STORE_RATE != value))
				{
					this._STORE_RATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_CODE", DbType="NVarChar(100)")]
		public string PRODUCT_CODE
		{
			get
			{
				return this._PRODUCT_CODE;
			}
			set
			{
				if ((this._PRODUCT_CODE != value))
				{
					this._PRODUCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_NAME", DbType="NVarChar(100)")]
		public string PRODUCT_NAME
		{
			get
			{
				return this._PRODUCT_NAME;
			}
			set
			{
				if ((this._PRODUCT_NAME != value))
				{
					this._PRODUCT_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH", DbType="NVarChar(250)")]
		public string BRANCH
		{
			get
			{
				return this._BRANCH;
			}
			set
			{
				if ((this._BRANCH != value))
				{
					this._BRANCH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_NAME", DbType="NVarChar(250)")]
		public string STATE_NAME
		{
			get
			{
				return this._STATE_NAME;
			}
			set
			{
				if ((this._STATE_NAME != value))
				{
					this._STATE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESIGNATION", DbType="NVarChar(100)")]
		public string DESIGNATION
		{
			get
			{
				return this._DESIGNATION;
			}
			set
			{
				if ((this._DESIGNATION != value))
				{
					this._DESIGNATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NAME", DbType="NVarChar(300)")]
		public string EMP_NAME
		{
			get
			{
				return this._EMP_NAME;
			}
			set
			{
				if ((this._EMP_NAME != value))
				{
					this._EMP_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="NVarChar(100)")]
		public string CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this._CreateUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyUser", DbType="NVarChar(100)")]
		public string ModifyUser
		{
			get
			{
				return this._ModifyUser;
			}
			set
			{
				if ((this._ModifyUser != value))
				{
					this._ModifyUser = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_PINZIPMASTERLIST")]
	public partial class MR_PINZIPMASTERLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _pin_id;
		
		private string _pin_code;
		
		private string _CITYNAME;
		
		private string _COUNTRYNAME;
		
		private string _STATENAME;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _CREATEUSER;
		
		private System.Nullable<System.DateTime> _MODIFYDATE;
		
		private string _MODIFYUSER;
		
		public MR_PINZIPMASTERLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pin_id", DbType="Int")]
		public System.Nullable<int> pin_id
		{
			get
			{
				return this._pin_id;
			}
			set
			{
				if ((this._pin_id != value))
				{
					this._pin_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pin_code", DbType="VarChar(10)")]
		public string pin_code
		{
			get
			{
				return this._pin_code;
			}
			set
			{
				if ((this._pin_code != value))
				{
					this._pin_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITYNAME", DbType="NVarChar(250)")]
		public string CITYNAME
		{
			get
			{
				return this._CITYNAME;
			}
			set
			{
				if ((this._CITYNAME != value))
				{
					this._CITYNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYNAME", DbType="NVarChar(250)")]
		public string COUNTRYNAME
		{
			get
			{
				return this._COUNTRYNAME;
			}
			set
			{
				if ((this._COUNTRYNAME != value))
				{
					this._COUNTRYNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATENAME", DbType="NVarChar(250)")]
		public string STATENAME
		{
			get
			{
				return this._STATENAME;
			}
			set
			{
				if ((this._STATENAME != value))
				{
					this._STATENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this._CREATEDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEUSER", DbType="NVarChar(100)")]
		public string CREATEUSER
		{
			get
			{
				return this._CREATEUSER;
			}
			set
			{
				if ((this._CREATEUSER != value))
				{
					this._CREATEUSER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFYDATE
		{
			get
			{
				return this._MODIFYDATE;
			}
			set
			{
				if ((this._MODIFYDATE != value))
				{
					this._MODIFYDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYUSER", DbType="NVarChar(100)")]
		public string MODIFYUSER
		{
			get
			{
				return this._MODIFYUSER;
			}
			set
			{
				if ((this._MODIFYUSER != value))
				{
					this._MODIFYUSER = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
