<?xml version="1.0" encoding="utf-8"?><Database Name="ModernRetail" Class="ModernRetailDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.MR_BRANCHDETAILSLIST" Member="MR_BRANCHDETAILSLISTs">
    <Type Name="MR_BRANCHDETAILSLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BRANCH_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRANCH_CODE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCHNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PARENTBRANCH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="BRANCH_ADDRESS1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BRANCH_COUNTRY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCH_STATE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCH_CITY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCH_PIN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_COUNTRYMASTERLIST" Member="MR_COUNTRYMASTERLISTs">
    <Type Name="MR_COUNTRYMASTERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="COUNTRYID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COUNTRYNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_STATEMASTERLIST" Member="MR_STATEMASTERLISTs">
    <Type Name="MR_STATEMASTERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="STATEID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATENAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="STATECODE" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="COUNTRYNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEUSER" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYUSER" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_DESIGNATIONMASTERLIST" Member="MR_DESIGNATIONMASTERLISTs">
    <Type Name="MR_DESIGNATIONMASTERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DESIGNATIONID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DESIGNATIONNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_USERLIST" Member="MR_USERLISTs">
    <Type Name="MR_USERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="UID" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="USER_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BRANCHNAME" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="REPORTTO" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DEG_DESIGNATION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_INACTIVE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_SECURITYROLESLIST" Member="MR_SECURITYROLESLISTs">
    <Type Name="MR_SECURITYROLESLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="GRP_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GRP_NAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_CITYMASTERLIST" Member="MR_CITYMASTERLISTs">
    <Type Name="MR_CITYMASTERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CITYID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITYNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="COUNTRYNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="STATENAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CityLocationLat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CityLocationLong" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEUSER" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYUSER" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>