<?xml version="1.0" encoding="utf-8"?><Database Name="ModernRetail" Class="ModernRetailDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.MR_BRANCHDETAILSLIST" Member="MR_BRANCHDETAILSLISTs">
    <Type Name="MR_BRANCHDETAILSLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="BRANCH_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BRANCH_CODE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCHNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="PARENTBRANCH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="BRANCH_ADDRESS1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="BRANCH_COUNTRY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCH_STATE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCH_CITY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="BRANCH_PIN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MR_COUNTRYMASTERLIST" Member="MR_COUNTRYMASTERLISTs">
    <Type Name="MR_COUNTRYMASTERLIST">
      <Column Name="USERID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEQ" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="COUNTRYID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="COUNTRYNAME" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>