#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernRetail.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ModernRetail")]
	public partial class ModernRetailDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ModernRetailDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModernRetailDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModernRetailDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ModernRetailDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MR_BRANCHDETAILSLIST> MR_BRANCHDETAILSLISTs
		{
			get
			{
				return this.GetTable<MR_BRANCHDETAILSLIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_COUNTRYMASTERLIST> MR_COUNTRYMASTERLISTs
		{
			get
			{
				return this.GetTable<MR_COUNTRYMASTERLIST>();
			}
		}
		
		public System.Data.Linq.Table<MR_STATEMASTERLIST> MR_STATEMASTERLISTs
		{
			get
			{
				return this.GetTable<MR_STATEMASTERLIST>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_BRANCHDETAILSLIST")]
	public partial class MR_BRANCHDETAILSLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _BRANCH_ID;
		
		private string _BRANCH_CODE;
		
		private string _BRANCHNAME;
		
		private string _PARENTBRANCH;
		
		private string _BRANCH_ADDRESS1;
		
		private string _BRANCH_COUNTRY;
		
		private string _BRANCH_STATE;
		
		private string _BRANCH_CITY;
		
		private string _BRANCH_PIN;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateUser;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyUser;
		
		public MR_BRANCHDETAILSLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_ID", DbType="Int")]
		public System.Nullable<int> BRANCH_ID
		{
			get
			{
				return this._BRANCH_ID;
			}
			set
			{
				if ((this._BRANCH_ID != value))
				{
					this._BRANCH_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_CODE", DbType="NVarChar(100)")]
		public string BRANCH_CODE
		{
			get
			{
				return this._BRANCH_CODE;
			}
			set
			{
				if ((this._BRANCH_CODE != value))
				{
					this._BRANCH_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCHNAME", DbType="NVarChar(250)")]
		public string BRANCHNAME
		{
			get
			{
				return this._BRANCHNAME;
			}
			set
			{
				if ((this._BRANCHNAME != value))
				{
					this._BRANCHNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PARENTBRANCH", DbType="NVarChar(250)")]
		public string PARENTBRANCH
		{
			get
			{
				return this._PARENTBRANCH;
			}
			set
			{
				if ((this._PARENTBRANCH != value))
				{
					this._PARENTBRANCH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_ADDRESS1", DbType="NVarChar(500)")]
		public string BRANCH_ADDRESS1
		{
			get
			{
				return this._BRANCH_ADDRESS1;
			}
			set
			{
				if ((this._BRANCH_ADDRESS1 != value))
				{
					this._BRANCH_ADDRESS1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_COUNTRY", DbType="NVarChar(100)")]
		public string BRANCH_COUNTRY
		{
			get
			{
				return this._BRANCH_COUNTRY;
			}
			set
			{
				if ((this._BRANCH_COUNTRY != value))
				{
					this._BRANCH_COUNTRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_STATE", DbType="NVarChar(100)")]
		public string BRANCH_STATE
		{
			get
			{
				return this._BRANCH_STATE;
			}
			set
			{
				if ((this._BRANCH_STATE != value))
				{
					this._BRANCH_STATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_CITY", DbType="NVarChar(100)")]
		public string BRANCH_CITY
		{
			get
			{
				return this._BRANCH_CITY;
			}
			set
			{
				if ((this._BRANCH_CITY != value))
				{
					this._BRANCH_CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BRANCH_PIN", DbType="NVarChar(100)")]
		public string BRANCH_PIN
		{
			get
			{
				return this._BRANCH_PIN;
			}
			set
			{
				if ((this._BRANCH_PIN != value))
				{
					this._BRANCH_PIN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="NVarChar(100)")]
		public string CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this._CreateUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyUser", DbType="NVarChar(100)")]
		public string ModifyUser
		{
			get
			{
				return this._ModifyUser;
			}
			set
			{
				if ((this._ModifyUser != value))
				{
					this._ModifyUser = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_COUNTRYMASTERLIST")]
	public partial class MR_COUNTRYMASTERLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _COUNTRYID;
		
		private string _COUNTRYNAME;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateUser;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyUser;
		
		public MR_COUNTRYMASTERLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYID", DbType="Int")]
		public System.Nullable<int> COUNTRYID
		{
			get
			{
				return this._COUNTRYID;
			}
			set
			{
				if ((this._COUNTRYID != value))
				{
					this._COUNTRYID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYNAME", DbType="NVarChar(250)")]
		public string COUNTRYNAME
		{
			get
			{
				return this._COUNTRYNAME;
			}
			set
			{
				if ((this._COUNTRYNAME != value))
				{
					this._COUNTRYNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUser", DbType="NVarChar(100)")]
		public string CreateUser
		{
			get
			{
				return this._CreateUser;
			}
			set
			{
				if ((this._CreateUser != value))
				{
					this._CreateUser = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyUser", DbType="NVarChar(100)")]
		public string ModifyUser
		{
			get
			{
				return this._ModifyUser;
			}
			set
			{
				if ((this._ModifyUser != value))
				{
					this._ModifyUser = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MR_STATEMASTERLIST")]
	public partial class MR_STATEMASTERLIST
	{
		
		private System.Nullable<int> _USERID;
		
		private System.Nullable<long> _SEQ;
		
		private System.Nullable<int> _STATEID;
		
		private string _STATENAME;
		
		private string _STATECODE;
		
		private string _COUNTRYNAME;
		
		private System.Nullable<System.DateTime> _CREATEDATE;
		
		private string _CREATEUSER;
		
		private System.Nullable<System.DateTime> _MODIFYDATE;
		
		private string _MODIFYUSER;
		
		public MR_STATEMASTERLIST()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", DbType="Int")]
		public System.Nullable<int> USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this._USERID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="BigInt")]
		public System.Nullable<long> SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this._SEQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATEID", DbType="Int")]
		public System.Nullable<int> STATEID
		{
			get
			{
				return this._STATEID;
			}
			set
			{
				if ((this._STATEID != value))
				{
					this._STATEID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATENAME", DbType="NVarChar(250)")]
		public string STATENAME
		{
			get
			{
				return this._STATENAME;
			}
			set
			{
				if ((this._STATENAME != value))
				{
					this._STATENAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATECODE", DbType="NVarChar(250)")]
		public string STATECODE
		{
			get
			{
				return this._STATECODE;
			}
			set
			{
				if ((this._STATECODE != value))
				{
					this._STATECODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYNAME", DbType="NVarChar(250)")]
		public string COUNTRYNAME
		{
			get
			{
				return this._COUNTRYNAME;
			}
			set
			{
				if ((this._COUNTRYNAME != value))
				{
					this._COUNTRYNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDATE
		{
			get
			{
				return this._CREATEDATE;
			}
			set
			{
				if ((this._CREATEDATE != value))
				{
					this._CREATEDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEUSER", DbType="NVarChar(100)")]
		public string CREATEUSER
		{
			get
			{
				return this._CREATEUSER;
			}
			set
			{
				if ((this._CREATEUSER != value))
				{
					this._CREATEUSER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIFYDATE
		{
			get
			{
				return this._MODIFYDATE;
			}
			set
			{
				if ((this._MODIFYDATE != value))
				{
					this._MODIFYDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIFYUSER", DbType="NVarChar(100)")]
		public string MODIFYUSER
		{
			get
			{
				return this._MODIFYUSER;
			}
			set
			{
				if ((this._MODIFYUSER != value))
				{
					this._MODIFYUSER = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
